/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Edict {
  id: string
  amount: bigint
  output: number
}
export interface BlockRange {
  start?: bigint
  end?: bigint
}
export interface Terms {
  amount?: bigint
  cap?: bigint
  height: BlockRange
  offset: BlockRange
}
export interface Etching {
  divisibility?: number
  premine?: bigint
  rune: string
  symbol: string
  terms?: Terms
  turbo: boolean
}
export interface Runestone {
  edicts: Array<Edict>
  etching?: Etching
  mint?: string
  pointer?: number
}
export function decipher(transaction: string): Runestone | null
export function encipher(data: Runestone): Buffer | null
